name: fire_circle
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/images/camp1.jpg
    - assets/images/camp2.png
    - assets/images/camp3.png
    - assets/images/camp4.jpg
    - assets/images/started2.jpg
    - assets/images/started3.jpg
    - assets/images/welcome.jpg
    - assets/images/camp_icon.png
    - assets/images/osusowake.png
    - assets/images/boad.png

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  adobe_xd: ^1.0.0+1
  entity: ^2.0.0
  firebase_core: ^1.1.0
  cloud_firestore: ^1.0.7
  flappy_search_bar: ^1.7.2
  responsive_x: ^0.1.1
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.2
  adobe_xd: ^1.0.0+1
  entity: ^2.0.0
